services:
  retreival-plugin:
    container_name: retrieval-plugin
    build:
      context: ./retrieval-plugin
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    env_file:
      - .env
    depends_on:
      - api-and-scraper
  api-and-scraper:
    container_name: api-and-scraper
    build:
      context: ./scraper
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
  client:
    container_name: client
    depends_on:
      - api-and-scraper
    build:
      context: ./askit-client
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"